intellij-idea-jetty-integration-plugin-3: NoSuchMethodError in the latest IDEA EAP build #98.231
 * build.properties : incremented minimum required build number of IDEA to 98.231.

 * JettyIntegration.iml : changed name of IDEA SDK to indicate minimum IDEA version required.

 * JettyStartupPolicy.java : replaced call to ProjectRootManager.getProjectJdk() with call to ProjectRootManager.getProjectSdk().